name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go install go.k6.io/xk6/cmd/xk6@latest
        xk6 build v0.32.0  --with github.com/AjayvirS/xk6-cognito="."
        


